import { NextResponse } from 'next/server';
import { auth } from '@/auth';
import { validatedAxiosRequest } from '@/lib/outbound-url';

// Safely format text to Atlassian Document Format (ADF) paragraph node
function textToAdfParagraph(text: string) {
  const clean = (text || '').trim();
  if (!clean) {
    return {
      type: 'paragraph',
      content: [],
    };
  }
  return {
    type: 'paragraph',
    content: [
      {
        type: 'text',
        text: clean,
      },
    ],
  };
}

function buildJiraDescriptionADF(payload: Record<string, any>) {
  const content: any[] = [];

  if (payload.description) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Description' }],
    });
    content.push(textToAdfParagraph(payload.description));
  }

  if (payload.steps_to_reproduce && Array.isArray(payload.steps_to_reproduce) && payload.steps_to_reproduce.length > 0) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Steps to Reproduce' }],
    });
    content.push({
      type: 'orderedList',
      content: payload.steps_to_reproduce
        .filter((step: string) => step && step.trim())
        .map((step: string) => ({
          type: 'listItem',
          content: [textToAdfParagraph(step)],
        })),
    });
  }

  if (payload.current_behavior) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Current Behavior' }],
    });
    content.push(textToAdfParagraph(payload.current_behavior));
  }

  if (payload.expected_result) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Expected Result' }],
    });
    content.push(textToAdfParagraph(payload.expected_result));
  }

  if (payload.actual_result) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Actual Result' }],
    });
    content.push(textToAdfParagraph(payload.actual_result));
  }

  if (payload.acceptance_criteria && Array.isArray(payload.acceptance_criteria) && payload.acceptance_criteria.length > 0) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Acceptance Criteria' }],
    });
    content.push({
      type: 'taskList',
      attrs: { localId: `task-list-${Date.now()}` },
      content: payload.acceptance_criteria
        .filter((c: string) => c && String(c).trim())
        .map((c: string, idx: number) => {
          const cleanText = String(c).replace(/^[-*]\s*(\[[ xX]\]\s*)?/, '').replace(/\*\*/g, '').trim();
          return {
            type: 'taskItem',
            attrs: {
              localId: `task-item-${Date.now()}-${idx}`,
              state: 'TODO',
            },
            content: [
              {
                type: 'text',
                text: cleanText,
              },
            ],
          };
        }),
    });
  }

  if (payload.evidence) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Evidence' }],
    });
    const evi = (payload.evidence || '').trim();
    const isUrl = /^https?:\/\//i.test(evi);
    if (isUrl) {
      content.push({
        type: 'paragraph',
        content: [
          {
            type: 'inlineCard',
            attrs: { url: evi },
          },
        ],
      });
    } else {
      content.push(textToAdfParagraph(evi));
    }
  }

  return {
    version: 1,
    type: 'doc',
    content: content.length > 0 ? content : [textToAdfParagraph('Generated by SnapTest')],
  };
}

export async function POST(request: Request) {
  try {
    if (!(await auth())?.user?.email) return NextResponse.json({ detail: 'Unauthorized' }, { status: 401 });
    const {
      auth_type,
      access_token,
      cloud_id,
      jira_domain,
      jira_email,
      jira_token,
      jira_project_key,
      issue_type,
      title,
      ...rest
    } = await request.json();

    if (!jira_project_key) {
      return NextResponse.json({ detail: 'Default Project Key is required' }, { status: 400 });
    }
    if (!title) {
      return NextResponse.json({ detail: 'Title is required to create a Jira issue' }, { status: 400 });
    }

    const isOAuth = auth_type === 'oauth2' && !!access_token;
    if (!isOAuth && (!jira_domain || !jira_email || !jira_token)) {
      return NextResponse.json({ detail: 'Jira settings incomplete. Please configure Jira in Settings.' }, { status: 400 });
    }

    let destination = '';
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      Accept: 'application/json',
    };

    let cleanDomain = (jira_domain || '').replace(/^https?:\/\//, '').replace(/\/$/, '');

    if (isOAuth) {
      if (!cloud_id || !/^[A-Za-z0-9-]+$/.test(cloud_id)) {
        return NextResponse.json({ detail: 'Jira OAuth workspace is invalid. Reconnect Jira in Settings.' }, { status: 400 });
      }
      destination = `https://api.atlassian.com/ex/jira/${cloud_id}/rest/api/3/issue`;
      headers['Authorization'] = `Bearer ${access_token.trim()}`;
    } else {
      destination = `https://${cleanDomain}/rest/api/3/issue`;
      const authHeader = Buffer.from(`${jira_email.trim()}:${jira_token.trim()}`).toString('base64');
      headers['Authorization'] = `Basic ${authHeader}`;
    }
    const projectKey = jira_project_key.trim().toUpperCase();

    // Map AI issue type directly to Jira exact work types: Bug, Improvement, New Feature, Task
    let mappedType = 'Bug';
    const rawType = (issue_type || '').trim().toLowerCase();

    if (rawType.includes('improvement')) {
      mappedType = 'Improvement';
    } else if (rawType.includes('feature')) {
      mappedType = 'New Feature';
    } else if (rawType.includes('task')) {
      mappedType = 'Task';
    } else {
      mappedType = 'Bug';
    }

    // Map AI priority (P0/P1/P2/P3) to Jira standard priorities (Highest, High, Medium, Low)
    let mappedPriority: string | null = null;
    const rawPriority = (rest.priority || '').trim().toUpperCase();
    if (rawPriority === 'P0' || rawPriority.includes('CRITICAL') || rawPriority.includes('HIGHEST') || rawPriority.includes('BLOCKER')) {
      mappedPriority = 'Highest';
    } else if (rawPriority === 'P1' || rawPriority.includes('HIGH')) {
      mappedPriority = 'High';
    } else if (rawPriority === 'P2' || rawPriority.includes('MEDIUM')) {
      mappedPriority = 'Medium';
    } else if (rawPriority === 'P3' || rawPriority.includes('LOW')) {
      mappedPriority = 'Low';
    } else if (mappedType === 'Bug') {
      mappedPriority = 'High';
    } else {
      mappedPriority = 'Medium';
    }

    const adfDescription = buildJiraDescriptionADF({ ...rest, description: rest.description });

    const jiraFields: Record<string, any> = {
      project: { key: projectKey },
      summary: title.replace(/\s+/g, ' ').trim().substring(0, 250),
      issuetype: { name: mappedType },
      description: adfDescription,
    };

    if (mappedPriority) {
      jiraFields.priority = { name: mappedPriority };
    }

    const jiraBody = { fields: jiraFields };

    let res;
    try {
      res = await validatedAxiosRequest(destination, {
        method: 'POST',
        data: jiraBody,
        headers,
        timeout: 15000,
      });
    } catch (createErr: any) {
      // Fallback: If Jira project schema does not include/allow the 'priority' field, retry without priority
      if (createErr.response?.data?.errors?.priority && jiraFields.priority) {
        delete jiraFields.priority;
        res = await validatedAxiosRequest(destination, {
          method: 'POST',
          data: { fields: jiraFields },
          headers,
          timeout: 15000,
        });
      } else {
        throw createErr;
      }
    }
    if (res.status >= 400) throw new Error('Jira rejected the request');

    const issueKey = res.data.key;
    const issueUrl = cleanDomain ? `https://${cleanDomain}/browse/${issueKey}` : `https://api.atlassian.com/ex/jira/${cloud_id}/browse/${issueKey}`;

    return NextResponse.json({
      success: true,
      issue_key: issueKey,
      issue_url: issueUrl,
    });
  } catch (err) {
    console.error('Jira create failed:', err);
    return NextResponse.json({ detail: 'Failed to create Jira issue' }, { status: 500 });
  }
}
