import { NextResponse } from 'next/server';
import { auth } from '@/auth';
import { validatedAxiosRequest } from '@/lib/outbound-url';

function textToAdfParagraph(text: string) {
  const clean = (text || '').trim();
  if (!clean) {
    return {
      type: 'paragraph',
      content: [],
    };
  }
  return {
    type: 'paragraph',
    content: [
      {
        type: 'text',
        text: clean,
      },
    ],
  };
}

function buildJiraDescriptionADF(payload: Record<string, any>) {
  const content: any[] = [];

  if (payload.description) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Description' }],
    });
    content.push(textToAdfParagraph(payload.description));
  }

  if (payload.steps_to_reproduce && Array.isArray(payload.steps_to_reproduce) && payload.steps_to_reproduce.length > 0) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Steps to Reproduce' }],
    });
    content.push({
      type: 'orderedList',
      content: payload.steps_to_reproduce
        .filter((step: string) => step && step.trim())
        .map((step: string) => ({
          type: 'listItem',
          content: [textToAdfParagraph(step)],
        })),
    });
  }

  if (payload.current_behavior) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Current Behavior' }],
    });
    content.push(textToAdfParagraph(payload.current_behavior));
  }

  if (payload.expected_result) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Expected Result' }],
    });
    content.push(textToAdfParagraph(payload.expected_result));
  }

  if (payload.actual_result) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Actual Result' }],
    });
    content.push(textToAdfParagraph(payload.actual_result));
  }

  if (payload.acceptance_criteria && Array.isArray(payload.acceptance_criteria) && payload.acceptance_criteria.length > 0) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Acceptance Criteria' }],
    });
    content.push({
      type: 'taskList',
      attrs: { localId: `task-list-${Date.now()}` },
      content: payload.acceptance_criteria
        .filter((c: string) => c && String(c).trim())
        .map((c: string, idx: number) => {
          const cleanText = String(c).replace(/^[-*]\s*(\[[ xX]\]\s*)?/, '').replace(/\*\*/g, '').trim();
          return {
            type: 'taskItem',
            attrs: {
              localId: `task-item-${Date.now()}-${idx}`,
              state: 'TODO',
            },
            content: [
              {
                type: 'text',
                text: cleanText,
              },
            ],
          };
        }),
    });
  }

  if (payload.evidence) {
    content.push({
      type: 'heading',
      attrs: { level: 3 },
      content: [{ type: 'text', text: 'Evidence' }],
    });
    const evi = (payload.evidence || '').trim();
    const urls = evi.match(/https?:\/\/[^\s,]+/gi) || [];
    if (urls.length > 0) {
      (Array.from(new Set(urls)) as string[]).forEach((url: string) => {
        content.push({
          type: 'paragraph',
          content: [
            {
              type: 'inlineCard',
              attrs: { url: url.trim() },
            },
          ],
        });
      });
    } else {
      content.push(textToAdfParagraph(evi));
    }
  }

  return {
    version: 1,
    type: 'doc',
    content: content.length > 0 ? content : [textToAdfParagraph('Generated by SnapTest')],
  };
}

export async function PUT(request: Request) {
  try {
    const session = await auth();
    if (!session?.user?.email) {
      return NextResponse.json({ detail: 'Unauthorized' }, { status: 401 });
    }

    const {
      issue_key,
      auth_type,
      access_token,
      cloud_id,
      jira_domain,
      jira_email,
      jira_token,
      title,
      ...rest
    } = await request.json();

    if (!issue_key || !String(issue_key).trim()) {
      return NextResponse.json({ detail: 'Issue Key is required to update a Jira issue' }, { status: 400 });
    }
    const cleanIssueKey = String(issue_key).trim().toUpperCase();

    const isOAuth = auth_type === 'oauth2' && !!access_token;
    if (!isOAuth && (!jira_domain || !jira_email || !jira_token)) {
      return NextResponse.json({ detail: 'Jira settings incomplete. Please configure Jira in Settings.' }, { status: 400 });
    }

    let destination = '';
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      Accept: 'application/json',
    };

    const cleanDomain = (jira_domain || '').replace(/^https?:\/\//, '').replace(/\/$/, '');

    if (isOAuth) {
      if (!cloud_id || !/^[A-Za-z0-9-]+$/.test(cloud_id)) {
        return NextResponse.json({ detail: 'Jira OAuth workspace is invalid. Reconnect Jira in Settings.' }, { status: 400 });
      }
      destination = `https://api.atlassian.com/ex/jira/${cloud_id}/rest/api/3/issue/${cleanIssueKey}`;
      headers['Authorization'] = `Bearer ${access_token.trim()}`;
    } else {
      destination = `https://${cleanDomain}/rest/api/3/issue/${cleanIssueKey}`;
      const authHeader = Buffer.from(`${jira_email.trim()}:${jira_token.trim()}`).toString('base64');
      headers['Authorization'] = `Basic ${authHeader}`;
    }

    const jiraFields: Record<string, any> = {};

    if (title && String(title).trim()) {
      jiraFields.summary = String(title).replace(/\s+/g, ' ').trim().substring(0, 250);
    }

    const adfDescription = buildJiraDescriptionADF({ ...rest, description: rest.description });
    jiraFields.description = adfDescription;

    // Priority mapping
    if (rest.priority) {
      const rawPriority = String(rest.priority).trim().toUpperCase();
      let mappedPriority: string | null = null;
      if (rawPriority === 'P0' || rawPriority.includes('CRITICAL') || rawPriority.includes('HIGHEST') || rawPriority.includes('BLOCKER')) {
        mappedPriority = 'Highest';
      } else if (rawPriority === 'P1' || rawPriority.includes('HIGH')) {
        mappedPriority = 'High';
      } else if (rawPriority === 'P2' || rawPriority.includes('MEDIUM')) {
        mappedPriority = 'Medium';
      } else if (rawPriority === 'P3' || rawPriority.includes('LOW')) {
        mappedPriority = 'Low';
      }
      if (mappedPriority) {
        jiraFields.priority = { name: mappedPriority };
      }
    }

    const assigneeAccountId = rest.assignee_id || rest.assignee_account_id || rest.assignee?.accountId || null;
    if (assigneeAccountId) {
      jiraFields.assignee = { accountId: assigneeAccountId };
    }

    const jiraBody = { fields: jiraFields };

    let res;
    try {
      res = await validatedAxiosRequest(destination, {
        method: 'PUT',
        data: jiraBody,
        headers,
        timeout: 15000,
      });
    } catch (updateErr: any) {
      // Fallback: If Jira project schema rejects priority or assignee, retry with sanitized fields
      const errors = updateErr.response?.data?.errors || {};
      let modified = false;
      if (errors.priority && jiraFields.priority) {
        delete jiraFields.priority;
        modified = true;
      }
      if (errors.assignee && jiraFields.assignee) {
        delete jiraFields.assignee;
        modified = true;
      }
      if (modified) {
        res = await validatedAxiosRequest(destination, {
          method: 'PUT',
          data: { fields: jiraFields },
          headers,
          timeout: 15000,
        });
      } else {
        const errorDetail = updateErr.response?.data?.errorMessages?.join(', ') ||
          JSON.stringify(errors) ||
          updateErr.message;
        throw new Error(`Jira update failed: ${errorDetail}`);
      }
    }

    if (res.status >= 400) {
      throw new Error(`Jira rejected update with status ${res.status}`);
    }

    return NextResponse.json({
      success: true,
      issue_key: cleanIssueKey,
      message: `Jira issue ${cleanIssueKey} updated successfully`,
    });
  } catch (err: any) {
    console.error('Jira update failed:', err);
    return NextResponse.json(
      { detail: err.message || 'Failed to update Jira issue' },
      { status: 500 }
    );
  }
}
